name: papaya
version: 0.0.1+2
author: Nicolas Francois  <nicolas.franc@gmail.com>
description: Commons library inspired by Guava
homepage: https://github.com/nfrancois/papaya
dev_dependencies:
  unittest: any
